# serverless.yml

service: hot-express

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'requests-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:Updateitem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["RequestsDynamoDBTable", "Arn" ] }
  environment:
    REQUESTS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getRequest:
    handler: index.handler
    events:
      - http: 'GET /requests/{proxy+}'
  createRequest:
    handler: index.handler
    events:
      - http: 'POST /requests'

resources:
  Resources:
    RequestsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: requestId
            AttributeType: S
        KeySchema:
          -
            AttributeName: requestId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}